export interface IUser{
    login: string,
    id?: number,
    followers?: number,
    following?: number,
    blog?: string,
    name?: string,
    avatar_url: string,
    html_url: string,
    bio: string | null,
    repos_url: string,
    company: string,
    location: string,
    public_repos: number,
    public_gists: number,
    created_at: string,
}