export interface userInt{
    login: string,
    id?: number,
    followers: number,
    following: number,
    blog: string,
    name: string,
    avatar_url: string,
    gravatar_id: string,
    url: string,
    html_url: string,
    followers_url: string,
    following_url: string,
    gists_url: string,
    starred_url: string,
    subscriptions_url: string,
    organizations_url: string,
    repos_url: string,
    events_url: string,
    received_events_url: string,
    type: string,
    site_admin: boolean,
    company: string,
    location: string,
    email: string | null,
    hireable: string | null,
    bio: string | null,
    twitter_username: string,
    public_repos: number,
    public_gists: number,
    created_at: string,
    updated_at: string
}